# Generated by Django 4.0.1 on 2022-01-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asksrories',
            new_name='Askstories',
        ),
        migrations.AlterField(
            model_name='newstories',
            name='kids',
            field=models.TextField(default='--', null=True),
        ),
        migrations.AlterField(
            model_name='newstories',
            name='time',
            field=models.IntegerField(default='--'),
        ),
        migrations.AlterField(
            model_name='newstories',
            name='url',
            field=models.CharField(default='--', max_length=200),
        ),
    ]
